### ISSUE TITLE
Remove this repository

### ISSUE THREAD

**Issue by Odonno** [jason-roberts/FeatureToggle.Docs#2]
Why creating another repository for the documentation if you use gh-pages ?

Indeed, like it is described here https://pages.github.com/, you can use the _gh-pages_ branch in your main repository (https://github.com/jason-roberts/FeatureToggle).

**Comment by jason-roberts** [comment]
Hi, thanks @Odonno - I did have this originally, don't recall why I decided to move to separate repo, I'm actually going to improve the docs by using another service such as https://readme.io/ - not decided which one yet though, so this repo will disappear at some point  see: https://github.com/jason-roberts/FeatureToggle/issues/83
